#!/usr/bin/env php
<?php

require_once './vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
# add our commands
$application->add(new GreetCommand());

$application->run();